# Generated by Django 4.2.7 on 2026-06-15 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dispatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dispatch_number", models.CharField(max_length=50, unique=True)),
                ("dispatch_date", models.DateField()),
                ("total_cartons", models.IntegerField()),
                ("total_quantity", models.IntegerField()),
                ("shipping_line", models.CharField(max_length=200)),
                ("vessel_name", models.CharField(blank=True, max_length=200)),
                ("container_number", models.CharField(blank=True, max_length=50)),
                ("bl_number", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("dispatched", "Dispatched"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.buyer"
                    ),
                ),
                (
                    "style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.style"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fabric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fabric_code", models.CharField(max_length=50, unique=True)),
                ("fabric_name", models.CharField(max_length=200)),
                ("color", models.CharField(max_length=50)),
                ("gsm", models.IntegerField()),
                ("width", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("meter", "Meter"),
                            ("kg", "Kilogram"),
                            ("yard", "Yard"),
                        ],
                        default="meter",
                        max_length=20,
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "reorder_level",
                    models.DecimalField(decimal_places=2, default=1000, max_digits=10),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FabricRoll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roll_number", models.CharField(max_length=50, unique=True)),
                ("lot_number", models.CharField(max_length=50)),
                ("length", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "used_length",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "remaining_length",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("location", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_stock", "In Stock"),
                            ("issued", "Issued"),
                            ("finished", "Finished"),
                        ],
                        default="in_stock",
                        max_length=20,
                    ),
                ),
                ("received_date", models.DateField()),
                (
                    "fabric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.fabric",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoodsReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_number", models.CharField(max_length=50, unique=True)),
                ("receipt_date", models.DateField(auto_now_add=True)),
                ("invoice_number", models.CharField(max_length=100)),
                (
                    "total_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "rejected_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "accepted_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "quality_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("inspected", "Inspected"),
                            ("rejected", "Rejected"),
                            ("accepted", "Accepted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("inspector_name", models.CharField(blank=True, max_length=100)),
                ("inspection_notes", models.TextField(blank=True)),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.purchaseorder",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductionIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue_number", models.CharField(max_length=50, unique=True)),
                ("issue_date", models.DateField()),
                ("issued_by", models.CharField(max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.style"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trim_code", models.CharField(max_length=50, unique=True)),
                ("trim_name", models.CharField(max_length=200)),
                (
                    "trim_type",
                    models.CharField(
                        choices=[
                            ("thread", "Thread"),
                            ("button", "Button"),
                            ("zipper", "Zipper"),
                            ("label", "Label"),
                            ("elastic", "Elastic"),
                            ("others", "Others"),
                        ],
                        max_length=50,
                    ),
                ),
                ("unit", models.CharField(max_length=20)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("current_stock", models.IntegerField(default=0)),
                ("reorder_level", models.IntegerField(default=500)),
                (
                    "supplier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.supplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductionIssueDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "issued_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "fabric",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.fabric",
                    ),
                ),
                (
                    "fabric_roll",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.fabricroll",
                    ),
                ),
                (
                    "production_issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.productionissue",
                    ),
                ),
                (
                    "trim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.trim",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoodsReceiptDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "accepted_quantity",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "rejected_quantity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "fabric",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.fabric",
                    ),
                ),
                (
                    "goods_receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.goodsreceipt",
                    ),
                ),
                (
                    "trim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.trim",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinishedGoods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku_code", models.CharField(max_length=50, unique=True)),
                ("size", models.CharField(max_length=20)),
                ("color", models.CharField(max_length=50)),
                ("quantity_produced", models.IntegerField(default=0)),
                ("quantity_in_stock", models.IntegerField(default=0)),
                ("quantity_dispatched", models.IntegerField(default=0)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("warehouse_location", models.CharField(max_length=100)),
                (
                    "style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.style"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DispatchDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carton_number", models.CharField(max_length=50)),
                ("quantity", models.IntegerField()),
                (
                    "dispatch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inventory.dispatch",
                    ),
                ),
                (
                    "finished_goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.finishedgoods",
                    ),
                ),
            ],
        ),
    ]
