# Generated by Django 4.2.7 on 2026-07-10 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hr", "0003_alter_leave_leave_type"),
        ("accounts", "0002_bankaccount_banktransaction_costsheet_payment_and_more"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dispatch",
            options={"ordering": ["-dispatch_date"]},
        ),
        migrations.AlterModelOptions(
            name="fabric",
            options={"ordering": ["fabric_code"]},
        ),
        migrations.AlterModelOptions(
            name="fabricroll",
            options={"ordering": ["-received_date"]},
        ),
        migrations.AlterModelOptions(
            name="finishedgoods",
            options={"ordering": ["style__style_number", "size", "color"]},
        ),
        migrations.AlterModelOptions(
            name="goodsreceipt",
            options={"ordering": ["-receipt_date"]},
        ),
        migrations.AlterModelOptions(
            name="productionissue",
            options={"ordering": ["-issue_date"]},
        ),
        migrations.AlterModelOptions(
            name="trim",
            options={"ordering": ["trim_code"]},
        ),
        migrations.RemoveField(
            model_name="goodsreceiptdetail",
            name="accepted_quantity",
        ),
        migrations.RemoveField(
            model_name="goodsreceiptdetail",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="goodsreceiptdetail",
            name="rejected_quantity",
        ),
        migrations.RemoveField(
            model_name="productionissuedetail",
            name="issued_quantity",
        ),
        migrations.RemoveField(
            model_name="productionissuedetail",
            name="quantity",
        ),
        migrations.AddField(
            model_name="dispatch",
            name="bl_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispatch",
            name="container_size",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="dispatch",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dispatch",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dispatches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dispatch",
            name="ex_factory_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dispatch",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dispatch",
            name="shipping_agent",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="dispatch",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="dispatch",
            name="vessel_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="dispatchdetail",
            name="carton_dimensions",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="dispatchdetail",
            name="carton_weight",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="dispatchdetail",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fabric",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fabric",
            name="current_stock",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="fabric",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fabric",
            name="fabric_type",
            field=models.CharField(
                choices=[
                    ("cotton", "Cotton"),
                    ("polyester", "Polyester"),
                    ("denim", "Denim"),
                    ("silk", "Silk"),
                    ("wool", "Wool"),
                    ("linen", "Linen"),
                    ("blend", "Blend"),
                    ("other", "Other"),
                ],
                default="cotton",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="fabric",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="fabric",
            name="max_stock",
            field=models.DecimalField(decimal_places=2, default=99999, max_digits=10),
        ),
        migrations.AddField(
            model_name="fabric",
            name="min_stock",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="fabric",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="fabricroll",
            name="bin_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="fabricroll",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fabricroll",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fabricroll",
            name="inspection_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fabricroll",
            name="inspector_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="fabricroll",
            name="quality_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Inspection"),
                    ("passed", "Passed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="fabricroll",
            name="rack_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="fabricroll",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="finishedgoods",
            name="bin_location",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="finishedgoods",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="finishedgoods",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="finishedgoods",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="finishedgoods",
            name="maximum_stock",
            field=models.IntegerField(default=99999),
        ),
        migrations.AddField(
            model_name="finishedgoods",
            name="minimum_stock",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="finishedgoods",
            name="quantity_defective",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="finishedgoods",
            name="rack_location",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="finishedgoods",
            name="reorder_level",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="finishedgoods",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="inspection_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="invoice_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="receipt_type",
            field=models.CharField(
                choices=[
                    ("fabric", "Fabric Receipt"),
                    ("trim", "Trim Receipt"),
                    ("both", "Both"),
                ],
                default="both",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="received_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_goods",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="goodsreceipt",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="goodsreceiptdetail",
            name="quantity_accepted",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goodsreceiptdetail",
            name="quantity_received",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goodsreceiptdetail",
            name="quantity_rejected",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="goodsreceiptdetail",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goodsreceiptdetail",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productionissue",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productionissue",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issues",
                to="hr.department",
            ),
        ),
        migrations.AddField(
            model_name="productionissue",
            name="production_line",
            field=models.CharField(default="DEF", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productionissue",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("issued", "Issued"),
                    ("partially_used", "Partially Used"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="productionissue",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="productionissuedetail",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="productionissuedetail",
            name="quantity_issued",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productionissuedetail",
            name="quantity_requested",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productionissuedetail",
            name="quantity_returned",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="productionissuedetail",
            name="quantity_used",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="productionissuedetail",
            name="waste_quantity",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="trim",
            name="color",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="trim",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trim",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="trim",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="trim",
            name="max_stock",
            field=models.IntegerField(default=99999),
        ),
        migrations.AddField(
            model_name="trim",
            name="min_stock",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="trim",
            name="size",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="trim",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="dispatch",
            name="buyer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dispatches",
                to="accounts.buyer",
            ),
        ),
        migrations.AlterField(
            model_name="dispatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("dispatched", "Dispatched"),
                    ("shipped", "Shipped"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="dispatch",
            name="style",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dispatches",
                to="accounts.style",
            ),
        ),
        migrations.AlterField(
            model_name="dispatchdetail",
            name="finished_goods",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dispatch_items",
                to="inventory.finishedgoods",
            ),
        ),
        migrations.AlterField(
            model_name="fabric",
            name="gsm",
            field=models.IntegerField(help_text="Grams per square meter"),
        ),
        migrations.AlterField(
            model_name="fabric",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fabrics",
                to="accounts.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="fabric",
            name="unit",
            field=models.CharField(
                choices=[
                    ("meter", "Meter"),
                    ("kg", "Kilogram"),
                    ("yard", "Yard"),
                    ("roll", "Roll"),
                ],
                default="meter",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="fabric",
            name="width",
            field=models.DecimalField(
                decimal_places=2, help_text="Width in inches", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="fabricroll",
            name="fabric",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rolls",
                to="inventory.fabric",
            ),
        ),
        migrations.AlterField(
            model_name="fabricroll",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_stock", "In Stock"),
                    ("issued", "Issued to Production"),
                    ("finished", "Fully Used"),
                    ("damaged", "Damaged"),
                    ("returned", "Returned to Supplier"),
                ],
                default="in_stock",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="finishedgoods",
            name="style",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="finished_goods",
                to="accounts.style",
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceipt",
            name="purchase_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="accounts.purchaseorder",
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceipt",
            name="quality_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Inspection"),
                    ("inspected", "Inspected"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("partial", "Partially Accepted"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceipt",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receipts",
                to="accounts.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceiptdetail",
            name="fabric",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipt_items",
                to="inventory.fabric",
            ),
        ),
        migrations.AlterField(
            model_name="goodsreceiptdetail",
            name="trim",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="receipt_items",
                to="inventory.trim",
            ),
        ),
        migrations.AlterField(
            model_name="productionissue",
            name="issued_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issued_materials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="productionissue",
            name="style",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="accounts.style",
            ),
        ),
        migrations.AlterField(
            model_name="productionissuedetail",
            name="fabric",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issue_items",
                to="inventory.fabric",
            ),
        ),
        migrations.AlterField(
            model_name="productionissuedetail",
            name="fabric_roll",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issue_items",
                to="inventory.fabricroll",
            ),
        ),
        migrations.AlterField(
            model_name="productionissuedetail",
            name="trim",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issue_items",
                to="inventory.trim",
            ),
        ),
        migrations.AlterField(
            model_name="trim",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trims",
                to="accounts.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="trim",
            name="trim_type",
            field=models.CharField(
                choices=[
                    ("thread", "Thread"),
                    ("button", "Button"),
                    ("zipper", "Zipper"),
                    ("label", "Label"),
                    ("elastic", "Elastic"),
                    ("ribbon", "Ribbon"),
                    ("lace", "Lace"),
                    ("tag", "Tag"),
                    ("hook", "Hook & Loop"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movement_number", models.CharField(max_length=50, unique=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("receipt", "Goods Receipt"),
                            ("issue", "Production Issue"),
                            ("return", "Return to Store"),
                            ("adjustment", "Stock Adjustment"),
                            ("transfer", "Transfer Between Locations"),
                            ("dispatch", "Dispatch to Buyer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reference_number", models.CharField(max_length=100)),
                ("reference_id", models.IntegerField()),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("from_location", models.CharField(blank=True, max_length=100)),
                ("to_location", models.CharField(blank=True, max_length=100)),
                ("movement_date", models.DateField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fabric",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements",
                        to="inventory.fabric",
                    ),
                ),
                (
                    "fabric_roll",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements",
                        to="inventory.fabricroll",
                    ),
                ),
                (
                    "finished_goods",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements",
                        to="inventory.finishedgoods",
                    ),
                ),
                (
                    "trim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movements",
                        to="inventory.trim",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adjustment_number", models.CharField(max_length=50, unique=True)),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("damage", "Damage Write-off"),
                            ("expired", "Expired Stock"),
                            ("qc_failure", "QC Failure"),
                            ("recount", "Recount Adjustment"),
                            ("return", "Return to Supplier"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("adjustment_date", models.DateField()),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reason", models.TextField()),
                ("approved_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fabric",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adjustments",
                        to="inventory.fabric",
                    ),
                ),
                (
                    "fabric_roll",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adjustments",
                        to="inventory.fabricroll",
                    ),
                ),
                (
                    "finished_goods",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adjustments",
                        to="inventory.finishedgoods",
                    ),
                ),
                (
                    "trim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="adjustments",
                        to="inventory.trim",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinishedGoodsProduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_number", models.CharField(max_length=50, unique=True)),
                ("production_date", models.DateField()),
                ("quantity_produced", models.IntegerField()),
                ("quantity_defective", models.IntegerField(default=0)),
                ("quantity_good", models.IntegerField()),
                ("production_line", models.CharField(max_length=50)),
                ("supervisor", models.CharField(max_length=100)),
                (
                    "quality_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending QC"),
                            ("passed", "Passed"),
                            ("rejected", "Rejected"),
                            ("partial", "Partially Passed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "finished_goods",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_batches",
                        to="inventory.finishedgoods",
                    ),
                ),
                (
                    "style",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_batches",
                        to="accounts.style",
                    ),
                ),
            ],
            options={
                "ordering": ["-production_date"],
            },
        ),
    ]
