# Generated by Django 4.2.7 on 2026-06-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employment_type",
            field=models.CharField(
                choices=[("monthly", "Monthly Salary"), ("contractual", "Contractual")],
                max_length=20,
            ),
        ),
    ]
