# Generated by Django 4.2.7 on 2026-07-10 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hr", "0002_alter_employee_employment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leave",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("sick", "Sick Leave"),
                    ("casual", "Casual Leave"),
                    ("unpaid", "Unpaid Leave"),
                ],
                max_length=20,
            ),
        ),
    ]
